language: python

notifications:
  webhooks: https://coveralls.io/webhook

jobs:
  include:
    - python: 3.6
      before_install:
      - sudo -E env "PATH=$PATH" pip3 install -U pip
      install:
      - sudo -E env "PATH=$PATH" pip install -e .[test]
      script:
      - sudo -E env "PATH=$PATH" pytest --cov=./src
      - bash <(curl -s https://codecov.io/bash) -cF python
    - python: 3.7
      before_install:
      - sudo -E env "PATH=$PATH" pip3 install -U pip
      install:
      - sudo -E env "PATH=$PATH" pip install -e .[test]
      script:
      - sudo -E env "PATH=$PATH" pytest --cov=./src
      - bash <(curl -s https://codecov.io/bash) -cF python
    - python: 3.8
      before_install:
      - sudo -E env "PATH=$PATH" pip3 install -U pip
      install:
      - sudo -E env "PATH=$PATH" pip install -e .[test]
      script:
      - sudo -E env "PATH=$PATH" pytest --cov=./src
      - bash <(curl -s https://codecov.io/bash) -cF python
    - name: "python 3.6 [Job failure permitted]"
      python: 3.6
      before_install:
      - pip3 install -U pip
      install:
      - pip install -e .[test]
      script:
      - pytest --cov=./src
      - bash <(curl -s https://codecov.io/bash) -cF python
  allow_failures:
    - name: "python 3.6 [Job failure permitted]"

after_success:
  - coveralls